{
    "coord" =  {
        "lon":10.5,"lat":51.5
    },
    "weather"= [{
        "id":501,"main":"Rain","description":"moderate rain","icon":"10d"
    }],
    "base" = "stations",
    "main" = {
        "temp":282.09,
        "feels_like":280.08,
        "temp_min":281.13,
        "temp_max":283.97,
        "pressure":999,
        "humidity":95,
        "sea_level":999,
        "grnd_level":963
    },
    "visibility" = 5307,
    "wind" = {
        "speed":3.54,"deg":201,"gust":8.42
    },
    "rain" = {
        "1h":1.22
    },
    "clouds" = {
        "all":100
    },
    "dt" = 1680255106,
    "sys" = {
        "type":2,
        "id":74551,
        "country":"DE",
        "sunrise":1680238588,
        "sunset":1680284869
    },
    "timezone" = 7200,
    "id" = 2921044,
    "name" = "Germany",
    "cod" = 200
}